### ISSUE TITLE
How to use phantom with com.stratio.cassandra.lucene

### ISSUE THREAD

**Issue by Croyson** [outworkers/phantom#481]
How to use phantom with com.stratio.cassandra.lucene!

**Comment by alexflav23** [comment]
Hi @Croyson,

We have planned a full integration with the Solr integartion of DSE and therefore Lucene compatibility inside phantom but we don't yet have it ready or plan to include it in the free version of phantom. We are on the verge of launching a subscription based license for phantom where you can unlock all the super powerful features of DSE, such as native Spark support via `phantom-spark`, automated data migrations, Solr/Lucene integration, UDT support, and much much more.

If you would like to, send me an email and I will add you to a list and let you know immediately as the new product is out, sounds like it would solve your problem and much more!

Regards.

**Comment by mmatloka** [comment]
Link to Stratio cassandra-lucene-index project :) https://github.com/Stratio/cassandra-lucene-index

**Comment by alexflav23** [comment]
hi @mmatloka,

Seems I mistakenly assumed this is the DSE native integration of Spark, we will consider how much work is involved in supporting this properly, it's hard to tell in the span of a few minutes, but obviously if it's doable and useful to a lot of people we will get it out, if it's more enterprise we will include it in the subscription version just because it's very difficult to justify spending a lot of development time on things that make no money to cover their expenses, as much as we wish we could match the OSS efforts of a company like Google or Facebook.

Regards.
