### ISSUE TITLE
resolving diesel-engine_2.11;0.3.0:

### ISSUE THREAD

**Issue by AvihayTsayeg** [outworkers/phantom#528]
I'm trying to use this project, getting problem resolving the diesel-engine_2.11.

```
sbt.ResolveException: unresolved dependency: com.websudos#diesel-engine_2.11;0.3.0: not found
```

I added all of these  

```
resolvers ++= Seq(
  Classpaths.typesafeReleases,
  Resolver.bintrayRepo("websudos", "oss-releases"),
  "oss-releases" at  "https://bintray.com/websudos/oss-releases",
  "oss-releases1" at "https://dl.bintray.com/websudos/oss-releases",
)
```

and all other in this [guide](https://github.com/outworkers/phantom/wiki/Integrating-phantom-in-your-project)
but no good ...

the odd here is that I can see the version in the repo [here](https://bintray.com/package/files/websudos/oss-releases/diesel-engine?order=asc&sort=name&basePath=com%2Fwebsudos%2Fdiesel-engine_2.11%2F0.3.0&tab=files)

but not in the [list](https://dl.bintray.com/websudos/oss-releases/com/websudos/diesel_2.11/) the repo expose ...

**Comment by alexflav23** [comment]
This is too much, maybe they are clashing:

```
resolvers ++= Seq(
  Classpaths.typesafeReleases,
  Resolver.bintrayRepo("websudos", "oss-releases"),
  "oss-releases" at  "https://bintray.com/websudos/oss-releases",
  "oss-releases1" at "https://dl.bintray.com/websudos/oss-releases",
)```

Just do this, see if it works.

```
resolvers ++= Seq(
  Classpaths.typesafeReleases,
  Resolver.bintrayRepo("websudos", "oss-releases")
```

**Comment by AvihayTsayeg** [comment]
Thx,
I started with this configuration and got the same result.

**Comment by alexflav23** [comment]
Hi @AvihayTsayeg, that's very strange.

- What version of phantom are you using?
- Are you sure the resolver settings are added to all the sub modules of your `build.sbt` if there are any? E.g. do you have any `val sharedSettings = ...` that don't get added to all modules or similar?

Regards.

**Comment by AvihayTsayeg** [comment]
Hi, 
I'm trying to use phantom_dsl 1.27.0 Scala 2.11.
I have one module.

If you search at the repo for diesel- engine_2.11;0.3.0

**Comment by AvihayTsayeg** [comment]
Sorry using mobile...
At the repo when searching for the diesel the artifact does appear in the results. diesel-engine_2.11;0.3.0

**Comment by AvihayTsayeg** [comment]
Hi, 
I'm trying to evaluate phantom-dsl 1.27.0 Scala 2.11.
I have single module, using sbt.
At the jfrog artifactory gui repo when searching for the diesel-engine the artifact does not appear in the results. diesel-engine_2.11;0.3.0

**Comment by alexflav23** [comment]
Make sure you have the right resolvers in place, the artefact in question is [here](https://bintray.com/websudos/oss-releases/diesel-engine) on Bintray, it's a critical one for phantom to work so if it didn't resolve no one would be using phantom.

My point being that makes me quite confident the issue is something local, maybe the network. It's really strange.

**Comment by AvihayTsayeg** [comment]
This is a simple example of my project, it does not compile
```
[error] (*:update) sbt.ResolveException: unresolved dependency: com.websudos#diesel-engine_2.11;0.3.0: not found

```
[phantomtest.zip](https://github.com/outworkers/phantom/files/405451/phantomtest.zip)

**Comment by AvihayTsayeg** [comment]
in your repo you have
![image](https://cloud.githubusercontent.com/assets/702139/17462229/2e61a644-5caf-11e6-8df5-cd7ca0a54fb0.png)

and as well you have
![image](https://cloud.githubusercontent.com/assets/702139/17462233/465638d2-5caf-11e6-9ad3-7a0580d1aac3.png)

the diesel appears in the first one only

**Comment by alexflav23** [comment]
Hi @AvihayTsayeg,

Can you add your build definition here or to a Gist and link to it? You can rename any sensitive settings or organisation names to whatever you like.

Regards.

**Comment by jumpOut** [comment]
Hi @AvihayTsayeg, 

I have the same issue, what's wrong you did?

**build.sbt**

```
val phantomV = "1.29.5"

libraryDependencies ++= Seq(
"com.websudos" %% "phantom-dsl" % phantomV exclude("ch.qos.logback", "logback-classic"),
  "com.websudos" %% "phantom-reactivestreams" % phantomV exclude("ch.qos.logback", "logback-classic")
)
```

**plugins.sbt**
```
resolvers ++= Seq(
   Resolver.bintrayRepo("websudos", "oss-releases")
)
```

**Comment by AvihayTsayeg** [comment]
Hi @jumpOut ,
My issue was putting the dependency in the plugin.sbt and not in the build.sbt.
It seems you have the correct dependencies.

did you add the resolver ?
```
resolvers ++= Seq(
  Classpaths.typesafeReleases,
  Resolver.bintrayRepo("websudos", "oss-releases")
)
```

**Comment by PiotrTrzpil** [comment]
I'm having similar issue today, when upgrading to the newest phantom version.
```
com.outworkers#diesel-engine_2.11;0.4.1: not found
```
Could the problem be because if two paths in the bintray repo, strangely resembling each other, as shown by ... on a screen above?

1. Directory: https://dl.bintray.com/websudos/oss-releases/com/websudos/ contains both diesel-engine_2.11/ and phantom-dsl_2.11/ directories
2. Directory: https://dl.bintray.com/websudos/oss-releases/com.websudos/ contains only phantom-dsl_2.11/ directory (of the above two)

Could the root issue be that diesel-engine_2.11/ is missing from the second directory?

**Comment by SKropiwnicki** [comment]
@PiotrTrzpil 
Having exactly same issue right now. Could it be more of a global problem? Maybe we could work around this by forcing sbt to download other diesel-engine version. 
Anyway if you find solution please post it. Will do same.

**Comment by youngkingtut** [comment]
Also having issues, looks like this url is returning a forbidden
https://dl.bintray.com/websudos/oss-releases/com/websudos/diesel-engine_2.10/0.3.0/diesel-engine_2.10-0.3.0.pom

**Comment by SKropiwnicki** [comment]
Well, today it works perfectly fine. Looks like it wasn't any of our fault here yesterday.
However it may cause worry about using something so unreliable. It caused quite a havoc in our team, cause of deadline. Anyone can tell if it even happened before?

**Comment by alexflav23** [comment]
HI @SKropiwnicki,

This is because of Bintray, we have moved from websudos to outworkers but asked them to keep the old repositories in place until all previous artefacts get published to Maven Central. Half way to that process something happened on their end and everyone started getting 403s.

Not a lot we could do other than email support and continue with publishing to Maven Central. After This week, we will no longer publish official releases to Bintray at all, it will be Maven Central exclusively for phantom and all of its dependencies so this will never happen again.

Hope this helps and apologies for any inconvenience caused!

Regards,
Flavian

**Comment by alexflav23** [comment]
Hi @AvihayTsayeg for the benefit of everyone here, phantom 1.29.6 and above is exclusively based on Maven Central including all dependencies. The websudos resolver will be going away for good shortly, but upgrading to this version should prevent any problems whatsoever from occurring.
