### ISSUE TITLE
The Risk of Assumptions: Multiple Database Connections in Phantom

### ISSUE THREAD

**Issue by fosskers** [outworkers/phantom#533]
Hi Phantom team. A few weeks ago I was in contact  with @alexflav23 in your Gitter, discussing  threading issues and the canonical way of shutting down a Phantom connection/session.

The issues were birthed from a strange beast: the use of [Apache Spark](https://spark.apache.org/), [Scalaz Streams](https://github.com/scalaz/scalaz-stream), and Phantom all at once. 

* Spark, to parallelise operations across machines
* Scalaz Streams, for fine-grained thread control within a Spark node
* Phantom, for Cassandra access via vanilla `Future`s

The setup was something like the following:

```scala
 import com.websudos.phantom.dsl._  // The import recommended by the Phantom guides.                      

 def foo[T](
   rdd: RDD[Whatever],
   getKeySpace: () => KeySpaceDef,
   getFooClient: () => FooClient,
   getContext: () => ExecutionContext
 ): Unit = {

   rdd.foreachPartition({ partition =>
     val fooClient = getFooClient()
     implicit val ex = getContext()
     val keyspace = getKeySpace()
     val cassandraDB = new MyDB[T](keyspace)

     /* A custom threadpool for control over scalaz-streams */
     val pool = Executors.newFixedThreadPool(...)

     /* For each element in the `partition`. Blocking. */
     val results = { ... use `pool`, talk to `cassandraDB`, talk to `fooClient` ... }

     /* All async Phantom/Scalaz tasks should be completed by now */
     pool.shutdown()
     cassandraDB.shutdown()  // Recommended by Flavian.                                                   

   })

 }
``` 

Unfortunately I can't link to the actual code sample, but the above should be a close enough description. The `() => T` pattern is used as a work-around to avoid `KeySpaceDef` and `FooClient` needing to be `Serializable`, as objects living in a Spark `Task` need to be. We thought it best to create a `MyDB[T]` connection per partition (node), as it wasn't clear what serializing a database connection would even mean, conceptually. Long term, there was no guarantee that the Spark `Task`s would run on the same machine.

Suffice to say, the setup above didn't work. The Cassandra interaction would only partially complete, and `NullPointException`s would emerge from the abyss to haunt our afternoon. Upon closer inspection of Phantom's `DatabaseImpl` class, we noticed [the following](https://github.com/outworkers/phantom/blob/develop/phantom-dsl/src/main/scala/com/websudos/phantom/database/DatabaseImpl.scala#L51):

```scala
  def shutdown(): Unit = {
    blocking {
      com.websudos.phantom.Manager.shutdown()
      session.getCluster.close()
      session.close()
    }
}
```
and then, in [the Manager object](https://github.com/outworkers/phantom/blob/develop/phantom-dsl/src/main/scala/com/websudos/phantom/Manager.scala#L38):

```scala

object Manager {

  private[this] lazy val taskExecutor = Executors.newCachedThreadPool()

...

  def shutdown(): Unit = {
    logger.info("Shutting down executors")
    taskExecutor.shutdown()
  }
}
```

whereby any `shutdown` call of anything that extends `Database` will kill a static reference to an Executor in a static object, and prevent any other database from functioning.

**Question**: By design, does Phantom assume that there will only be one database connection per application? 

The answer seems to be yes, but that doesn't fit our use case. We've had to alter our original code above to:

```scala
 import com.websudos.phantom.dsl.KeySpaceDef  // To avoid stray execution contexts.

 def foo[T](...): Unit = {

   rdd.foreachPartition({ partition =>
     ...

     /* A custom threadpool for control over scalaz-streams */
     val pool = Executors.newFixedThreadPool(...)

     ...

     /* All async Phantom/Scalaz tasks should be completed by now */
     pool.shutdown()

     /* Call down to datastax ourselves */
     keySpaceDef.session.getCluster.close()
     keySpaceDef.session.close()              

   })

 }

...

// In our testing suite, after all operations are complete.
Manager.shutdown()
```

We noticed some conflicts with execution contexts as well, so we opted not to import all of `dsl._`. This is clearly not idiomatic Phantom usage, but we had to do it this way to avoid the exceptions.

Would it be possible to make `Database`s (same keyspace or not) truly modular, such that many could be spun up and shutdown in a single application?

**Comment by mmatloka** [comment]
hi @fosskers,
I've very strong doubts if it is the right way to use Spark.
a) When you use standard spark cassandra connector, it is not possible to peform cassandra queries from insde transformations - cassandra context would be null as it is available only in driver process and is not "replicated" to nodes during execution - it is some type of sign its not the right way ;)
b) 
> We thought it best to create a MyDB[T] connection per partition (node), as it wasn't clear what serializing a database connection would even mean, conceptually. Long term, there was no guarantee that the Spark Tasks would run on the same machine.

this case is not really about having multiple phantom connections, but about creating and stopping them inside the spark transformations. The whole related logic would have to be executed inside the `foreachPartition`. The connection releted objects created outside of it might not be serialized and sent to proper node as it needs connections between execution node and cassandra instead of driver node and cassandra
c) I would be careful with using phantom with spark. Spark cassandra connector is optimized for queries on the spark cluster. It automagically queries data from local token ranges, saves data to local nodes etc. You might have later performance issues. Additionally refering to `Scalaz Streams, for fine-grained thread control within a Spark node` - can't spark manage threads by itself? ;) just configure it to proper numer of cores, create proper number of partitions etc. I would rather recommend to stick with [spark cassandra connector](https://github.com/datastax/spark-cassandra-connector).

**Comment by alexflav23** [comment]
Hi @fosskers @mmatloka,

I would kind of have to agree with @mmatloka on the fact that phantom isn't truly optimised for Spark usage, it's designed to be the one stop destination for the application level usage of Cassandra but not really inside a Spark cluster. 

There is way too much duplication of concern in between what Spark already does at a very different level and what phantom is meant to do for an app, and that includes a lot of things like threading control and so on, which are implemented very very differently between the two as they suit a different purpose.

In terms of taste palette and Scala usage, the Spark connector doesn't win me as audience in that sense, which is why we are working hard to ship our own **phantom-spark**, a fully type-safe no reflection type of product(something we will roll out to phantom itself too) and that will give you a more streamlined experience using Spark as well.

But as @mmatloka points out, achieving data locality properly is obviously not even a concern for the normal **phantom-dsl** as we never had Spark usage in mind at the time of designing all this. 

Regards,
Flavian

**Comment by fosskers** [comment]
We ended up getting something working with Spark for the local case, but we're not positive of behaviour in a truly distributed environment.
