### ISSUE TITLE
Persistence of MapColumn[String, ByteBuffer] broken?

### ISSUE THREAD

**Issue by cmacher** [outworkers/phantom#548]
When I define a column as type `MapColumn[String, ByteBuffer] ` and store and retrieve an entry I get as value back not only the original value but also the key. So when I store for instance:

`("title" -> "test")`

I get back something like:

`("title" -> "title test")`

To demonstrate it I have forked the project and create a test for it:
https://github.com/cmacher/phantom/blob/develop/phantom-example/src/test/scala/com/websudos/phantom/example/ExampleSuite.scala

**Comment by alexflav23** [comment]
Hi @cmacher,

It definitely looks like it is, I think the `ByteBuffer` offset is reading from the beginning of the entire serialised row, otherwise I cannot see why this would happen`. Given in your test you are not doing anything to manipulate the outcome this is indeed a phantom bug, by all means many thanks for reporting it.

If you would like to take a shot at fixing the issue, basically the `MapColumn` results will get parsed using `Primitive[ByteBuffer].fromPrimitive`, which seems to be the cause of the problem here. It's a bit interesting, as the `fromPrimitive` method only received the `value` as an argument.

Have a look [here](https://github.com/outworkers/phantom/blob/faa29f1eaf1dbba16746423d9e6ef13041ee491e/phantom-dsl/src/main/scala/com/websudos/phantom/column/MapColumn.scala#L89), this is the code that basically dictates how a `Map` is parsed back.

Regards.

**Comment by cmacher** [comment]
Wow. Impressively quick feedback. I will give it a shot fixing it.

**Comment by cmacher** [comment]
Turns out it wasn't a bug. I was not using the `ByteBuffer` correctly when converting it back into the serialized object. I was using the backed array as a whole ignoring the position.

Wrong:
```
val ois = new ObjectInputStream(new ByteArrayInputStream(byteBuffer.array()))
val value = ois.readObject
```
Correct:
```
val bs = new Array[Byte](byteBuffer.remaining())
byteBuffer.get(bs)
val ois = new ObjectInputStream(new ByteArrayInputStream(bs))
val value = ois.readObject
```
