### ISSUE TITLE
Migrate to Cassandra 4.0 or 3.10

### ISSUE THREAD

**Issue by lahirug** [outworkers/phantom#568]
We are currently using phanton-dsl (1.23.4) with C* 2.1.11 cluster. We are thinking of migrating to newer C* version. I am curious about the client side support. 

What version does 1.23.4 supports ? Should we migrate the phantom-dsl too if we want to migrate to 3.10 or 4.0 ? 
What complication are we expected ? If you can point me to a document that would be helpful.

**Comment by alexflav23** [comment]
Hi @lahirug,

I'd expect you to be able to transparently update your Cassandra cluster, although obviously I would recommend that you use the most recent version of phantom if you can. 2.0.0 is being made available in a few days, so that will bring very very powerful improvements.

In an ideal world, you should have no problem upgrading, at least from the phantom side. The way phantom works is that we encode Cassandra backwards incompatibilities within phantom itself, so we have code that for instance is designated for protocol V1 and things like that.

With 4.0, things may have changed, but if you have issues, they are bugs on our end so please report them and we will get them fixed asap.

Regards,
Flavian

**Comment by lahirug** [comment]
@alexflav23 thanks. But I cannot find latest releases in https://dl.bintray.com/websudos/oss-releases/.

**Comment by alexflav23** [comment]
Hi @lahirug apologies, phantom 2.0.0 is available under https://dl.bintray.com/outworkers/oss-releases/, and Maven Central.
