### ISSUE TITLE
Surprising ScalaTest Output

### ISSUE THREAD

**Issue by peter-empen** [outworkers/phantom#582]
After upgrading to phantom-dsl 1.29.3, we experience some additional ScalaTest output when running specs2 Tests. Do you probably have an explanation?

The above phenomenon is easily reproducable by the following tiny project:
```
name := "phantom-test"
version := "1.0"
scalaVersion := "2.11.8"
libraryDependencies ++= Seq(
  "com.websudos" %% "phantom-dsl" % "1.29.3",
  "org.specs2" %% "specs2-core" % "3.8.6" % "test")
resolvers += "Websudos" at "https://dl.bintray.com/websudos/oss-releases/"

------------------- XSpec.scala:
import org.specs2.Specification

class XSpec extends Specification {
  def is = s2"""An example $e1"""

  def e1 = true
}
```

**Comment by alexflav23** [comment]
Hi @peter-empen,

Thank you for your feedback, that sounds rather strange, nothing to the best of our knowledge should have interfered with test output. Phantom does indeed rely on ScalaTest, but only as a `Test` scope dependency which doesn't get propagated to other codebases. There's a good reason we do this, namely because we cannot dictate the test framework for all our audience.

Regards,
Flavian

**Comment by peter-empen** [comment]
Hi Flavian,
that's all right but can you reproduce the phenomenon? If so, do you have an explanation where to dig further?

**Comment by alexflav23** [comment]
Hi @peter-empen

Yes, the root cause is accidental but has been spotted. The Diesel engine accidentally introduced ScalaTest as part of the `compile` scope which is nothing more than a terrible accidental mistake that has since been fixed.

A new release will be out today itself to address this.

Regards,

**Comment by peter-empen** [comment]
Great, thank you for looking into this.

**Comment by peter-empen** [comment]
Where can I find the new release of diesel-engine? I see just 0.4.1 from Sep 30 on bintray.

**Comment by alexflav23** [comment]
@peter-empen Maven Central, 0.5.0

**Comment by peter-empen** [comment]
Yeh, it works.
