### ISSUE TITLE
Bind values in prepared statements by their names 

### ISSUE THREAD

**Issue by oseval** [outworkers/phantom#639]
It will be nice to have ability like this:
```
select.all()
  .where(_.columnX eqs ?)
  .and(_.columnY eqs ?)
  .prepare
  .bind(_.columnX, valueX)
  .bind(_.columnY, valueY)
  .future
```

**Comment by alexflav23** [comment]
Hi @oseval,

I don't really see the value add over:

```scala
select.all()
  .where(_.columnX eqs ?)
  .and(_.columnY eqs ?)
  .prepare
  .bind(valueX, valueY)
  .future
```

It's just more verbose, but may there are use cases that are not obvious? If so please outline some.

**Comment by oseval** [comment]
It's just more safely:). If `columnX` is `Int` and `columnY` also `Int`, then how you will detect error if I wrote:
```
select.all()
  .where(_.columnX eqs ?)
  .and(_.columnY eqs ?)
  .prepare
  .bind(valueY, valueX)
  .future
```

It's easy to see error if you set value to a column with a name different from name of variable.

**Comment by oseval** [comment]
I have to note that actual code will look like this:
```
val someStatement = select.all()
  .where(_.columnX eqs ?)
  .and(_.columnY eqs ?)
  .prepare
...
a lot of code
...
def foo(Y, X) = someStatement
  .bind(valueY, valueX)
  .future
```

sometimes is find out too late to fix such error easily

**Comment by alexflav23** [comment]
Hi @oseval 

This is to avoid re-preparing statements, so there's a good reason why code looks like that, to give you a clear cutoff of controlling how statements get prepared. But I'll see what can be done, to mask the reprearing automatically.

Regards.

**Comment by alexflav23** [comment]
Hi @oseval,

We have registered an internal ticket to support this, but it's very low priority and we have decided to drop it for now. The reason is that `bind` is a one stop destination and currently acts as a final trigger, because you get a query result back.

There would be a non trivial amount of code to right here for very little benefit, and given we've not encountered this request in the past and that the error does occur at compile time, we are going to put this aside for now and focus on features that impact all users, which is currently developing native protocol parsers on #648 and other such high priority items.

If there are enough users looking for this feature, we will look at it again.

Regards.
