### ISSUE TITLE
Update record that matches multiple conditions causes a compilation error.

### ISSUE THREAD

**Issue by GRpro** [outworkers/phantom#683]
This issue is actually a duplicate of https://github.com/outworkers/phantom/issues/681
It was closed due to my mistake in code but the problem still exists for me.

Could you please help with it?

Thanks!

**Comment by alexflav23** [comment]
Hi @GRpro Can you paste your code properly then?

**Comment by GRpro** [comment]
Please, find below
```
import com.outworkers.phantom.dsl._

import scala.concurrent.Future

case class Item (
  item1: String,
  item2: String,
  weight: Double
)

class ItemsTable extends CassandraTable[Items, Item] {

  object  item1 extends StringColumn(this) with PartitionKey
  object  weight extends DoubleColumn(this) with ClusteringOrder with Descending
  object item2 extends StringColumn(this) with ClusteringOrder with Ascending


  override def fromRow(row: Row): Item = {
    Item(
      item1(row),
      item2(row),
      weight(row)
    )
  }
}

abstract class Items extends ItemsTable with RootConnector {
  def updateSimilarity(item: Item): Future[ResultSet] = {
    update
      .where(_.item1 eqs item.item1)
      .and(_.item2 eqs item.item2)
      .modify(_.weight setTo item.weight)
      .future()
  }
}
```
The error is
```
value setTo is not a member of object x$5.weight
[error]       .modify(_.weight setTo item.weight)
[error]                            ^
```

**Comment by alexflav23** [comment]
Hi @GRpro,

I finally realised what's wrong here, I think it's worth you reading more about how Cassandra keys work.. Because they are in effect map keys, they can never be updated, so you are "stuck". Upserts to primary keys means you have to re-insert records.

Clustering order keys become part of the primary, because that's how Cassandra orders data inside a partition. Some useful reading may be found [here](http://outworkers.com/blog/post/a-series-on-cassandra-part-1-getting-rid-of-the-sql-mentality).

Regards.
