### ISSUE TITLE
Unable to connect to Cassandra over SSL/TLS

### ISSUE THREAD

**Issue by inbanerj** [outworkers/phantom#708]
Our application is build in scala2.12 and Akka, it is connecting to Cassandra using Phantom Adapter it is working fine without SSL. once the SSL is enabled in the Cassandra database, we tried to connect using the trust-store it is not accessible. we are using the java options to pass the trustStore getting a error as follows:
======================================================
sbt -Djavax.net.debug=ssl -Djavax.net.ssl.trustStore=/Users/inbanerj/cdx/DevCenter/sandbox_keys/truststore_SUBROTO -Djavax.net.ssl.trustStorePassword=abc
========================ERROR LOG=======================
00E0: 79 06 8A 9B A6 4F D9 22   FA 44 4E 36 F3 C9 0F A6  y....O.".DN6....
00F0: 39 E7 80 B2 5E BF BD 39   D1 46 E5 55 47 DB BC 6E  9...^..9.F.UG..n

]
***
%% Invalidated:  [Session-1, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384]
default-akka.actor.default-dispatcher-3, SEND TLSv1.2 ALERT:  fatal, description = certificate_unknown
default-akka.actor.default-dispatcher-3, WRITE: TLSv1.2 Alert, length = 2
default-akka.actor.default-dispatcher-3, called closeSocket()
default-akka.actor.default-dispatcher-3, handling exception: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
default-akka.actor.default-dispatcher-3, called close()
default-akka.actor.default-dispatcher-3, called closeInternal(true)

**Comment by alexflav23** [comment]
There is very little we can do to help externally with this issue, I think the error has nothing to do with phantom but to do with a potentially misconfigured trust store.

I'd start here:

```scala
sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```
In the future please note it's difficult to give help on issues where we do not have the code and means to reproduce and as a result in spite of best attentions we generally cannot be helpful and do not cover this kind of support outside of a support license.

Double and triple check your trust store is setup as you expected it to be, and I think the problem is likely hiding there.

Regards,
Flavian
