### ISSUE TITLE
Understanding "Found multiple possible matches for" log message

### ISSUE THREAD

**Issue by NicolaeNMV** [outworkers/phantom#724]
Hello there,

I was wondering what's the meaning of "Found multiple possible matches for" that appears during the compilation time.

Here I am running phantom-example tests, and got this output:
```scala
[info] phantom/phantom-example/src/main/scala/com/outworkers/phantom/example/basics/SimpleRecipes.scala:50: Found multiple possible matches for name : String
[info] abstract class Recipes extends Table[Recipes, Recipe] {
[info]                                ^
[info] phantom/phantom-example/src/main/scala/com/outworkers/phantom/example/basics/SimpleRecipes.scala:50: Found multiple possible matches for title : String
[info] abstract class Recipes extends Table[Recipes, Recipe] {
[info]                                ^
[info] phantom/phantom-example/src/main/scala/com/outworkers/phantom/example/basics/SimpleRecipes.scala:50: Found multiple possible matches for author : String
[info] abstract class Recipes extends Table[Recipes, Recipe] {
```
Link to the referenced code: [SimpleRecipes.scala:50](https://github.com/outworkers/phantom/blob/develop/phantom-example/src/main/scala/com/outworkers/phantom/example/basics/SimpleRecipes.scala#L50)

```scala
//...
  object name extends StringColumn
  object title extends StringColumn
  object author extends StringColumn
//...
```

Is phantom trying to match columns by their type ?

If this is correct, I was wondering if there could be a way to explicitly set the mapping to avoid those messages ? As at first I thought that there could be a problem with my code and this may be misleading.

Kudos by the way for a great library.

**Comment by alexflav23** [comment]
Hi @NicolaeNMV, we are working on an implicit mechanism that will turn off all debug output by default, so in the next versions you will only see error logs. This is an unfortunate quirk of the Scala compiler, which is not meant to display `INFO` level logs by default during macro expansion, unless you explicitly enable them with a compiler flag.

However, the compiler itself does not respect the logging level, and that's what you are seeing right there. A new release will be out, and you will need to explicitly `import com.outworkers.phantom.debug.ShowDerivation` to see those logs, otherwise they will be hidden.

Glad you are enjoying the library!

**Comment by NicolaeNMV** [comment]
Sounds like a good idea, thanks for a prompt answer !
