### ISSUE TITLE
Struggling with ExecutionContextExecutor over the DSL model.

### ISSUE THREAD

**Issue by manypozo** [outworkers/phantom#730]
Hi guys,

I am trying out Phantom for a simple project but I am continuously having issues with the implicit ExecutionContextExecutor. I am trying to follow the guides from the GitHub basics, but it seems I am missing some points. 

My code is shared in this [GistHub](https://gist.github.com/manypozo/42b23ee005c756843178171da607e64b)

Somehow it seems like my `abstract xxModel extends Table[] with RootConnector` needs the scala.concurrent.ExecutionContextExecutor ;

```
Error:(63, 17) could not find implicit value for parameter ec:scala.concurrent.ExecutionContextExecutor
            .one()
```
```
Error:(63, 17) not enough arguments for method one: (implicit session: com.datastax.driver.core.Session, implicit ev: =:=[com.outworkers.phantom.builder.Unlimited,com.outworkers.phantom.builder.Unlimited], implicit ec: scala.concurrent.ExecutionContextExecutor)scala.concurrent.Future[Option[Ranking]].
Unspecified value parameter ec.
            .one()
```

I understand from the RootConnector and the second error that my methods need the ExecutionContextExecutor to work with the Future involved in the getById query.

What am I missing?   I have look all over the Internet for some more examples but most of them seem to use the old phantom versions (1.x) and others they simply do not have the ExecutionContextExecutor.. 

I know this is something of my implementation, but I can find it where is the issue! A little help please ? =]
Thank you very much !

**Comment by alexflav23** [comment]
Hi,

`import com.outworkers.phantom.dsl._` will provide you with a default `ExecutionContextExecutor` so that's pretty trivial. `ExecutionContextExecutor` is just a bridge between Java and Scala execution contexts so we can use it interchangeably internally when converting Guava futures returned by Cassandra's Java Driver to Scala futures, nothing more, so you can even provide your own implicit, but if all you are doing is getting used to things, stick to the basic provided via `import com.outworkers.phantom.dsl.context`.

Also, when you mixin `Table` instaed of `CassandraTable` you no longer need to mixin `RootConnector`, that's why we created `Table`, the other one is just there for legacy reasons to not break compilation for everyone.

Regards.

**Comment by manypozo** [comment]
Hi,
I came up with the same conclusion right now actually. 
I was wondering if the `ExecutionContextExecutor` was implicitly imported by one of these packages, so I started to verify all my imports one by one. It seems to work now =]

I am not sure if I read about the implicit import from `com.outworkers.phantom.dsl._` in the basics.md, section "Database is designed to be the final level of encapsulation".  I would suggest to make it more clear.

Thank you for your fast answer and explanation!
