### ISSUE TITLE
Request/Suggestion - make SelectQuery types covariant

### ISSUE THREAD

**Issue by 123avi** [outworkers/phantom#740]
Does it make sense to make SelectQuery types covariant ?
This way we can extend the library like this :

```
  implicit class Helper[A <: CassandraTable[A, _], R]
  (q: SelectQuery[A, R, _, _, _, _, _]) {
    def withOptionalLimit(limit: Option[Int]): SelectQuery[A, R, LimitBound, _, _, _, _] = {
      limit.map(l => q.limit(l)).getOrElse(q)
    }
  }
```

**Comment by alexflav23** [comment]
You can already do that, you just need to materialize all the type arguments properly instead of using `_`. In this particular case it will however be impossible to provide a generic return based on an `if else`. 

The type of the `LimitBound` argument is important to the other implicit conversions further down. These are called phantom types, and they need to be fully known at compile time, which is obviously impossible if they are based on the runtime value of an `Option`.

While you can augment `SelectQuery` already, you will not be able to conditionally return a different type bound and make it work. This is because the compiler will infer the lower common ancestor type for the phantom type, namely `LimitBound`, and then it won't be able to actually know if it's `Limited` or `Unlimited`. The whole value of phantom types is compile time predictability.

**Comment by 123avi** [comment]
Got it. In the previous version it worked (the code above) and I could actually could do something like 
```
select
    .where(...)
    .withOptionalLimit(limit)
    .fetch()
```
in version 2.14.1
I had to do something like this to make it which is not very elegant (but does the work, is it have performance impact ?):
```
 implicit class Helper[A <: CassandraTable[A, _], R,
  L <: LimitBound,
  O <: OrderBound,
  S <: ConsistencyBound,
  C <: WhereBound,
  P <: HList
  ](q: SelectQuery[A, R, L, O, S, C, P]) {
    def withOptionalLimit(limit: Option[Int])(
      implicit ev: L =:= Unlimited
    ): SelectQuery[A, R, Limited, O, S, C, P] = {
      limit.map(l => q.limit(l)).getOrElse(q.limit(Int.MaxValue))
    }
  }

```

**Comment by alexflav23** [comment]
The performance impact should be negligible as long as you make that a value class. With respect to the implementation, I genuinely do not se how it's possible unless you stick to the format in your first example.

The only thing that changes is you now need to `import com.outworkers.phantom.dsl._` where you define your implicit, because the kind of `Future` returned by phantom queries is now tied to the execution backend you import. `com.outworkers.phantom.dsl._` is Scala Futures, `com.outworkers.phantom.twitter._` is Twitter etc, there are a couple backends now.
