### ISSUE TITLE
Can we do spatial queries? If yes, then how?

### ISSUE THREAD

**Issue by amolpol98** [outworkers/phantom#843]

**Comment by alexflav23** [comment]
Hi @amolpol98 Spatial queries are part of Solr and the enterprise integration to Cassandra offered under DSE, as illustrated [here](https://docs.datastax.com/en/datastax_enterprise/4.8/datastax_enterprise/srch/srchSpatialQueries.html).

We do not offer support for this in phantom, though we do add support for Solr queries in `phantom-pro` only, our subscription based product. If you would like to learn more about that, feel free to get in touch at `flavian@outworkers.com`. That's a paid for version of phantom, it will do what you need, and we can enhance features to match your needs too.

For now, since you need Datastax Enterprise to access it, we don't include it in the OSS phantom and have no plans to.
