### ISSUE TITLE
Consider changing type of implicit `context` in DefaultImports

### ISSUE THREAD

**Issue by jalaziz** [outworkers/phantom#911]
While upgrading to Scala 2.12, we started seeing compiler errors that were a bit surprising. In particular, the imported `context` from phantom was taking precedence over implicit method parameters.

Scala actually changed the type of `ExecutionContext.Implicits.global` to ensure there's a compiler error when this happens unknowingly. See https://github.com/scala/bug/issues/8849 and https://github.com/scala/scala/commit/44953dcb08fc5dd92e423a56bd42bcc32757aaef.

It might make sense to do the same with the `context` in `DefaultImports`.

**Comment by alexflav23** [comment]
Hi @jalaziz,

This makes sense and it's an easy change. However, in practice could lead to trouble. We need to upcast back to `ExecutionContextExecutor` when we convert Java futures to Scala using the Guava library, that's something that happens behind the scenes because connection management is still done by the Java Driver. In fact, it's the only part of that driver we use, everything else is replaced by Scala native items.

https://github.com/outworkers/phantom/pull/912

Have a look here, this needs more thought before it can be merged, but it's simple enough to do in theory.

**Comment by jalaziz** [comment]
Yeah, I was thinking it might be possible to hide the upcast within the API.

Will take a look at the PR soon!
